var CARS_DATA = [
  {
    "id": 1,
    "brand": "BYD",
    "model": "海豹 650智驾版",
    "year": 2025,
    "price": 19833,
    "priceLabel": "$19,833",
    "mileage": "17000 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_1_1.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_1_1.jpg",
      "uploads/cars/car_1_2.jpg",
      "uploads/cars/car_1_3.jpg",
      "uploads/cars/car_1_4.jpg",
      "uploads/cars/car_1_5.jpg",
      "uploads/cars/car_1_6.jpg",
      "uploads/cars/car_1_7.jpg",
      "uploads/cars/car_1_8.jpg"
    ]
  },
  {
    "id": 2,
    "brand": "BYD",
    "model": "汉 DM-i 智驾版 125KM激光雷达旗舰型",
    "year": 2025,
    "price": 19417,
    "priceLabel": "$19,417",
    "mileage": "2300 km",
    "fuel_type": "PHEV",
    "transmission": "自动",
    "image": "uploads/cars/car_2_2.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_2_2.jpg",
      "uploads/cars/car_2_2.jpg",
      "uploads/cars/car_2_3.jpg",
      "uploads/cars/car_2_4.jpg",
      "uploads/cars/car_2_5.jpg",
      "uploads/cars/car_2_6.jpg",
      "uploads/cars/car_2_7.jpg",
      "uploads/cars/car_2_8.jpg"
    ]
  },
  {
    "id": 3,
    "brand": "BYD",
    "model": "宋PLUS新能源 DM-i 112KM 尊荣型",
    "year": 2025,
    "price": 13875,
    "priceLabel": "$13,875",
    "mileage": "11000 km",
    "fuel_type": "PHEV",
    "transmission": "自动",
    "image": "uploads/cars/car_3_3.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_3_3.jpg",
      "uploads/cars/car_3_2.jpg",
      "uploads/cars/car_3_3.jpg",
      "uploads/cars/car_3_4.jpg",
      "uploads/cars/car_3_5.jpg",
      "uploads/cars/car_3_6.jpg",
      "uploads/cars/car_3_7.jpg",
      "uploads/cars/car_3_8.jpg"
    ]
  },
  {
    "id": 4,
    "brand": "Chery",
    "model": "瑞虎8 PLUS 冠军版 290TGDI DCT豪享版 5座",
    "year": 2024,
    "price": 11917,
    "priceLabel": "$11,917",
    "mileage": "27000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_4_4.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_4_4.jpg",
      "uploads/cars/car_4_2.jpg",
      "uploads/cars/car_4_3.jpg",
      "uploads/cars/car_4_4.jpg",
      "uploads/cars/car_4_5.jpg",
      "uploads/cars/car_4_6.jpg",
      "uploads/cars/car_4_7.jpg",
      "uploads/cars/car_4_8.jpg"
    ]
  },
  {
    "id": 5,
    "brand": "Chery",
    "model": "瑞虎9 2.0T 自动两驱尊享版 5座",
    "year": 2025,
    "price": 16375,
    "priceLabel": "$16,375",
    "mileage": "4100 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_5_5.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_5_5.jpg",
      "uploads/cars/car_5_2.jpg",
      "uploads/cars/car_5_3.jpg",
      "uploads/cars/car_5_4.jpg",
      "uploads/cars/car_5_5.jpg",
      "uploads/cars/car_5_6.jpg",
      "uploads/cars/car_5_7.jpg",
      "uploads/cars/car_5_8.jpg"
    ]
  },
  {
    "id": 6,
    "brand": "Haval",
    "model": "哈弗大狗 2.0T DCT中华田园犬版",
    "year": 2026,
    "price": 18028,
    "priceLabel": "$18,028",
    "mileage": "100 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_6_6.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_6_6.jpg",
      "uploads/cars/car_6_2.jpg",
      "uploads/cars/car_6_3.jpg",
      "uploads/cars/car_6_4.jpg",
      "uploads/cars/car_6_5.jpg",
      "uploads/cars/car_6_6.jpg",
      "uploads/cars/car_6_7.jpg",
      "uploads/cars/car_6_8.jpg"
    ]
  },
  {
    "id": 7,
    "brand": "MG",
    "model": "名爵ZS 180DVVT 自动全球百万918版",
    "year": 2022,
    "price": 6806,
    "priceLabel": "$6,806",
    "mileage": "88000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_7_7.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_7_7.jpg",
      "uploads/cars/car_7_2.jpg",
      "uploads/cars/car_7_3.jpg",
      "uploads/cars/car_7_4.jpg",
      "uploads/cars/car_7_5.jpg",
      "uploads/cars/car_7_6.jpg",
      "uploads/cars/car_7_7.jpg",
      "uploads/cars/car_7_8.jpg"
    ]
  },
  {
    "id": 8,
    "brand": "Jetour",
    "model": "捷途X70 PLUS 冠军版 1.5T DCT冠军MAX+ 5座",
    "year": 2024,
    "price": 10389,
    "priceLabel": "$10,389",
    "mileage": "10000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_8_8.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_8_8.jpg",
      "uploads/cars/car_8_2.jpg",
      "uploads/cars/car_8_3.jpg",
      "uploads/cars/car_8_4.jpg",
      "uploads/cars/car_8_5.jpg",
      "uploads/cars/car_8_6.jpg",
      "uploads/cars/car_8_7.jpg",
      "uploads/cars/car_8_8.jpg"
    ]
  },
  {
    "id": 9,
    "brand": "Haval",
    "model": "哈弗H6 第三代 1.5T 自动两驱Max",
    "year": 2021,
    "price": 8306,
    "priceLabel": "$8,306",
    "mileage": "27200 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_9_9.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_9_9.jpg",
      "uploads/cars/car_9_2.jpg",
      "uploads/cars/car_9_3.jpg",
      "uploads/cars/car_9_4.jpg",
      "uploads/cars/car_9_5.jpg",
      "uploads/cars/car_9_6.jpg",
      "uploads/cars/car_9_7.jpg",
      "uploads/cars/car_9_8.jpg"
    ]
  },
  {
    "id": 10,
    "brand": "BYD",
    "model": "海鸥 智驾版 305km 活力版",
    "year": 2025,
    "price": 8306,
    "priceLabel": "$8,306",
    "mileage": "100 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_10_10.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_10_10.jpg",
      "uploads/cars/car_10_2.jpg",
      "uploads/cars/car_10_3.jpg",
      "uploads/cars/car_10_4.jpg",
      "uploads/cars/car_10_5.jpg",
      "uploads/cars/car_10_6.jpg",
      "uploads/cars/car_10_7.jpg",
      "uploads/cars/car_10_8.jpg"
    ]
  },
  {
    "id": 11,
    "brand": "BYD",
    "model": "秦PLUS DM-i 智驾版 55KM超越型",
    "year": 2025,
    "price": 7542,
    "priceLabel": "$7,542",
    "mileage": "15000 km",
    "fuel_type": "PHEV",
    "transmission": "自动",
    "image": "uploads/cars/car_11_11.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_11_11.jpg",
      "uploads/cars/car_11_2.jpg",
      "uploads/cars/car_11_3.jpg",
      "uploads/cars/car_11_4.jpg",
      "uploads/cars/car_11_5.jpg",
      "uploads/cars/car_11_6.jpg",
      "uploads/cars/car_11_7.jpg",
      "uploads/cars/car_11_8.jpg"
    ]
  },
  {
    "id": 12,
    "brand": "BYD",
    "model": "唐新能源 DM-i 冠军版 112KM 尊荣型",
    "year": 2023,
    "price": 14694,
    "priceLabel": "$14,694",
    "mileage": "49000 km",
    "fuel_type": "PHEV",
    "transmission": "自动",
    "image": "uploads/cars/car_12_12.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_12_12.jpg",
      "uploads/cars/car_12_2.jpg",
      "uploads/cars/car_12_3.jpg",
      "uploads/cars/car_12_4.jpg",
      "uploads/cars/car_12_5.jpg",
      "uploads/cars/car_12_6.jpg",
      "uploads/cars/car_12_7.jpg",
      "uploads/cars/car_12_8.jpg"
    ]
  },
  {
    "id": 13,
    "brand": "Chery",
    "model": "瑞虎8L 2.0T 两驱尊贵版 5座",
    "year": 2024,
    "price": 15250,
    "priceLabel": "$15,250",
    "mileage": "6000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_13_13.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_13_13.jpg",
      "uploads/cars/car_13_2.jpg",
      "uploads/cars/car_13_3.jpg",
      "uploads/cars/car_13_4.jpg",
      "uploads/cars/car_13_5.jpg",
      "uploads/cars/car_13_6.jpg",
      "uploads/cars/car_13_7.jpg",
      "uploads/cars/car_13_8.jpg"
    ]
  },
  {
    "id": 14,
    "brand": "Chery",
    "model": "艾瑞泽8 1.6T DCT卓越版",
    "year": 2025,
    "price": 9236,
    "priceLabel": "$9,236",
    "mileage": "3600 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_14_14.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_14_14.jpg",
      "uploads/cars/car_14_2.jpg",
      "uploads/cars/car_14_3.jpg",
      "uploads/cars/car_14_4.jpg",
      "uploads/cars/car_14_5.jpg",
      "uploads/cars/car_14_6.jpg",
      "uploads/cars/car_14_7.jpg",
      "uploads/cars/car_14_8.jpg"
    ]
  },
  {
    "id": 15,
    "brand": "Chery",
    "model": "欧萌达 1.5T CVT畅行版",
    "year": 2025,
    "price": 10944,
    "priceLabel": "$10,944",
    "mileage": "7000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_15_15.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_15_15.jpg",
      "uploads/cars/car_15_2.jpg",
      "uploads/cars/car_15_3.jpg",
      "uploads/cars/car_15_4.jpg",
      "uploads/cars/car_15_5.jpg",
      "uploads/cars/car_15_6.jpg",
      "uploads/cars/car_15_7.jpg",
      "uploads/cars/car_15_8.jpg"
    ]
  },
  {
    "id": 16,
    "brand": "Haval",
    "model": "哈弗大狗 1.5T DCT边牧版",
    "year": 2024,
    "price": 10667,
    "priceLabel": "$10,667",
    "mileage": "21900 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_16_16.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_16_16.jpg",
      "uploads/cars/car_16_2.jpg",
      "uploads/cars/car_16_3.jpg",
      "uploads/cars/car_16_4.jpg",
      "uploads/cars/car_16_5.jpg",
      "uploads/cars/car_16_6.jpg",
      "uploads/cars/car_16_7.jpg",
      "uploads/cars/car_16_8.jpg"
    ]
  },
  {
    "id": 17,
    "brand": "Haval",
    "model": "哈弗H6 国潮版 1.5T 自动冠军版",
    "year": 2023,
    "price": 12472,
    "priceLabel": "$12,472",
    "mileage": "30000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_17_17.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_17_17.jpg",
      "uploads/cars/car_17_2.jpg",
      "uploads/cars/car_17_3.jpg",
      "uploads/cars/car_17_4.jpg",
      "uploads/cars/car_17_5.jpg",
      "uploads/cars/car_17_6.jpg",
      "uploads/cars/car_17_7.jpg",
      "uploads/cars/car_17_8.jpg"
    ]
  },
  {
    "id": 18,
    "brand": "Haval",
    "model": "哈弗H9 2.0T 汽油四驱尊享型 5座",
    "year": 2020,
    "price": 14694,
    "priceLabel": "$14,694",
    "mileage": "36000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_18_18.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_18_18.jpg",
      "uploads/cars/car_18_2.jpg",
      "uploads/cars/car_18_3.jpg",
      "uploads/cars/car_18_4.jpg",
      "uploads/cars/car_18_5.jpg",
      "uploads/cars/car_18_6.jpg",
      "uploads/cars/car_18_7.jpg",
      "uploads/cars/car_18_8.jpg"
    ]
  },
  {
    "id": 19,
    "brand": "MG",
    "model": "MG7 1.5T DCT至美优雅版",
    "year": 2023,
    "price": 11917,
    "priceLabel": "$11,917",
    "mileage": "20000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_19_19.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_19_19.jpg",
      "uploads/cars/car_19_2.jpg",
      "uploads/cars/car_19_3.jpg",
      "uploads/cars/car_19_4.jpg",
      "uploads/cars/car_19_5.jpg",
      "uploads/cars/car_19_6.jpg",
      "uploads/cars/car_19_7.jpg",
      "uploads/cars/car_19_8.jpg"
    ]
  },
  {
    "id": 20,
    "brand": "MG",
    "model": "名爵ZS 180DVVT 自动全球百万918版",
    "year": 2022,
    "price": 6778,
    "priceLabel": "$6,778",
    "mileage": "88000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_20_20.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_20_20.jpg",
      "uploads/cars/car_20_2.jpg",
      "uploads/cars/car_20_3.jpg",
      "uploads/cars/car_20_4.jpg",
      "uploads/cars/car_20_5.jpg",
      "uploads/cars/car_20_6.jpg",
      "uploads/cars/car_20_7.jpg",
      "uploads/cars/car_20_8.jpg"
    ]
  },
  {
    "id": 21,
    "brand": "Great Wall",
    "model": "炮 2.0T乘用版自动汽油四驱尊享型GW4C20B",
    "year": 2023,
    "price": 18028,
    "priceLabel": "$18,028",
    "mileage": "15000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_21_21.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_21_21.jpg",
      "uploads/cars/car_21_2.jpg",
      "uploads/cars/car_21_3.jpg",
      "uploads/cars/car_21_4.jpg",
      "uploads/cars/car_21_5.jpg",
      "uploads/cars/car_21_6.jpg",
      "uploads/cars/car_21_7.jpg",
      "uploads/cars/car_21_8.jpg"
    ]
  },
  {
    "id": 22,
    "brand": "Great Wall",
    "model": "风骏5 2.0T 柴油两驱进取型大双",
    "year": 2023,
    "price": 8306,
    "priceLabel": "$8,306",
    "mileage": "40000 km",
    "fuel_type": "Diesel",
    "transmission": "手动",
    "image": "uploads/cars/car_22_22.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_22_22.jpg",
      "uploads/cars/car_22_2.jpg",
      "uploads/cars/car_22_3.jpg",
      "uploads/cars/car_22_4.jpg",
      "uploads/cars/car_22_5.jpg",
      "uploads/cars/car_22_6.jpg",
      "uploads/cars/car_22_7.jpg",
      "uploads/cars/car_22_8.jpg"
    ]
  },
  {
    "id": 23,
    "brand": "Roewe",
    "model": "荣威RX5 1.5T 超感精英版",
    "year": 2023,
    "price": 5694,
    "priceLabel": "$5,694",
    "mileage": "30000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_23_23.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_23_23.jpg",
      "uploads/cars/car_23_2.jpg",
      "uploads/cars/car_23_3.jpg",
      "uploads/cars/car_23_4.jpg",
      "uploads/cars/car_23_5.jpg",
      "uploads/cars/car_23_6.jpg",
      "uploads/cars/car_23_7.jpg",
      "uploads/cars/car_23_8.jpg"
    ]
  },
  {
    "id": 24,
    "brand": "Roewe",
    "model": "飞凡R7 进阶版",
    "year": 2024,
    "price": 11542,
    "priceLabel": "$11,542",
    "mileage": "25000 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_24_24.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_24_24.jpg",
      "uploads/cars/car_24_2.jpg",
      "uploads/cars/car_24_3.jpg",
      "uploads/cars/car_24_4.jpg",
      "uploads/cars/car_24_5.jpg",
      "uploads/cars/car_24_6.jpg",
      "uploads/cars/car_24_7.jpg",
      "uploads/cars/car_24_8.jpg"
    ]
  },
  {
    "id": 25,
    "brand": "Jetour",
    "model": "捷途旅行者 2.0T 四驱穿越PRO",
    "year": 2023,
    "price": 16667,
    "priceLabel": "$16,667",
    "mileage": "9600 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_25_25.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_25_25.jpg",
      "uploads/cars/car_25_2.jpg",
      "uploads/cars/car_25_3.jpg",
      "uploads/cars/car_25_4.jpg",
      "uploads/cars/car_25_5.jpg",
      "uploads/cars/car_25_6.jpg",
      "uploads/cars/car_25_7.jpg",
      "uploads/cars/car_25_8.jpg"
    ]
  },
  {
    "id": 26,
    "brand": "Jetour",
    "model": "捷途大圣 1.5T DCT 星耀PRO",
    "year": 2024,
    "price": 11639,
    "priceLabel": "$11,639",
    "mileage": "23700 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_26_26.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_26_26.jpg",
      "uploads/cars/car_26_2.jpg",
      "uploads/cars/car_26_3.jpg",
      "uploads/cars/car_26_4.jpg",
      "uploads/cars/car_26_5.jpg",
      "uploads/cars/car_26_6.jpg",
      "uploads/cars/car_26_7.jpg",
      "uploads/cars/car_26_8.jpg"
    ]
  },
  {
    "id": 27,
    "brand": "Avatr",
    "model": "阿维塔11 Ultra 增程版",
    "year": 2025,
    "price": 26917,
    "priceLabel": "$26,917",
    "mileage": "3000 km",
    "fuel_type": "PHEV",
    "transmission": "自动",
    "image": "uploads/cars/car_27_27.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_27_27.jpg",
      "uploads/cars/car_27_2.jpg",
      "uploads/cars/car_27_3.jpg",
      "uploads/cars/car_27_4.jpg",
      "uploads/cars/car_27_5.jpg",
      "uploads/cars/car_27_6.jpg",
      "uploads/cars/car_27_7.jpg",
      "uploads/cars/car_27_8.jpg"
    ]
  },
  {
    "id": 28,
    "brand": "Avatr",
    "model": "阿维塔12 改款 Max纯电版",
    "year": 2025,
    "price": 31667,
    "priceLabel": "$31,667",
    "mileage": "100 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_28_28.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_28_28.jpg",
      "uploads/cars/car_28_2.jpg",
      "uploads/cars/car_28_3.jpg",
      "uploads/cars/car_28_4.jpg",
      "uploads/cars/car_28_5.jpg",
      "uploads/cars/car_28_6.jpg",
      "uploads/cars/car_28_7.jpg",
      "uploads/cars/car_28_8.jpg"
    ]
  },
  {
    "id": 29,
    "brand": "NIO",
    "model": "蔚来ES6 75kWh",
    "year": 2024,
    "price": 22639,
    "priceLabel": "$22,639",
    "mileage": "28400 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_29_29.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_29_29.jpg",
      "uploads/cars/car_29_2.jpg",
      "uploads/cars/car_29_3.jpg",
      "uploads/cars/car_29_4.jpg",
      "uploads/cars/car_29_5.jpg",
      "uploads/cars/car_29_6.jpg",
      "uploads/cars/car_29_7.jpg",
      "uploads/cars/car_29_8.jpg"
    ]
  },
  {
    "id": 30,
    "brand": "NIO",
    "model": "蔚来ET5 75kWh",
    "year": 2025,
    "price": 20556,
    "priceLabel": "$20,556",
    "mileage": "26000 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_30_30.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_30_30.jpg",
      "uploads/cars/car_30_2.jpg",
      "uploads/cars/car_30_3.jpg",
      "uploads/cars/car_30_4.jpg",
      "uploads/cars/car_30_5.jpg",
      "uploads/cars/car_30_6.jpg",
      "uploads/cars/car_30_7.jpg",
      "uploads/cars/car_30_8.jpg"
    ]
  },
  {
    "id": 31,
    "brand": "XPeng",
    "model": "小鹏P7+ 长续航 Max",
    "year": 2024,
    "price": 20667,
    "priceLabel": "$20,667",
    "mileage": "5100 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_31_31.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_31_31.jpg",
      "uploads/cars/car_31_2.jpg",
      "uploads/cars/car_31_3.jpg",
      "uploads/cars/car_31_4.jpg",
      "uploads/cars/car_31_5.jpg",
      "uploads/cars/car_31_6.jpg",
      "uploads/cars/car_31_7.jpg",
      "uploads/cars/car_31_8.jpg"
    ]
  },
  {
    "id": 32,
    "brand": "XPeng",
    "model": "小鹏MONA M03 600 超长续航 Max",
    "year": 2025,
    "price": 15139,
    "priceLabel": "$15,139",
    "mileage": "12600 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_32_32.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_32_32.jpg",
      "uploads/cars/car_32_2.jpg",
      "uploads/cars/car_32_3.jpg",
      "uploads/cars/car_32_4.jpg",
      "uploads/cars/car_32_5.jpg",
      "uploads/cars/car_32_6.jpg",
      "uploads/cars/car_32_7.jpg",
      "uploads/cars/car_32_8.jpg"
    ]
  },
  {
    "id": 33,
    "brand": "Zeekr",
    "model": "极氪001 YOU版 100kWh 四驱",
    "year": 2025,
    "price": 31389,
    "priceLabel": "$31,389",
    "mileage": "2200 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_33_33.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_33_33.jpg",
      "uploads/cars/car_33_2.jpg",
      "uploads/cars/car_33_3.jpg",
      "uploads/cars/car_33_4.jpg",
      "uploads/cars/car_33_5.jpg",
      "uploads/cars/car_33_6.jpg",
      "uploads/cars/car_33_7.jpg",
      "uploads/cars/car_33_8.jpg"
    ]
  },
  {
    "id": 34,
    "brand": "Zeekr",
    "model": "极氪X 五座长续航版",
    "year": 2025,
    "price": 14583,
    "priceLabel": "$14,583",
    "mileage": "2000 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_34_34.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_34_34.jpg",
      "uploads/cars/car_34_2.jpg",
      "uploads/cars/car_34_3.jpg",
      "uploads/cars/car_34_4.jpg",
      "uploads/cars/car_34_5.jpg",
      "uploads/cars/car_34_6.jpg",
      "uploads/cars/car_34_7.jpg",
      "uploads/cars/car_34_8.jpg"
    ]
  },
  {
    "id": 35,
    "brand": "BYD",
    "model": "宋Pro新能源 第二代 DM-i 115KM超越型",
    "year": 2025,
    "price": 11361,
    "priceLabel": "$11,361",
    "mileage": "37900 km",
    "fuel_type": "PHEV",
    "transmission": "自动",
    "image": "uploads/cars/car_35_35.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_35_35.jpg",
      "uploads/cars/car_35_2.jpg",
      "uploads/cars/car_35_3.jpg",
      "uploads/cars/car_35_4.jpg",
      "uploads/cars/car_35_5.jpg",
      "uploads/cars/car_35_6.jpg",
      "uploads/cars/car_35_7.jpg",
      "uploads/cars/car_35_8.jpg"
    ]
  },
  {
    "id": 36,
    "brand": "BYD",
    "model": "海豚 智驾版 410km 时尚版",
    "year": 2025,
    "price": 11917,
    "priceLabel": "$11,917",
    "mileage": "5000 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_36_36.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_36_36.jpg",
      "uploads/cars/car_36_2.jpg",
      "uploads/cars/car_36_3.jpg",
      "uploads/cars/car_36_4.jpg",
      "uploads/cars/car_36_5.jpg",
      "uploads/cars/car_36_6.jpg",
      "uploads/cars/car_36_7.jpg",
      "uploads/cars/car_36_8.jpg"
    ]
  },
  {
    "id": 37,
    "brand": "Chery",
    "model": "瑞虎8 PRO 冠军版 290T 两驱巅峰版 7座",
    "year": 2024,
    "price": 12750,
    "priceLabel": "$12,750",
    "mileage": "15500 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_37_37.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_37_37.jpg",
      "uploads/cars/car_37_2.jpg",
      "uploads/cars/car_37_3.jpg",
      "uploads/cars/car_37_4.jpg",
      "uploads/cars/car_37_5.jpg",
      "uploads/cars/car_37_6.jpg",
      "uploads/cars/car_37_7.jpg",
      "uploads/cars/car_37_8.jpg"
    ]
  },
  {
    "id": 38,
    "brand": "Chery",
    "model": "艾瑞泽8 PRO 2.0T DCT 尊享型",
    "year": 2025,
    "price": 14139,
    "priceLabel": "$14,139",
    "mileage": "17560 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_38_38.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_38_38.jpg",
      "uploads/cars/car_38_2.jpg",
      "uploads/cars/car_38_3.jpg",
      "uploads/cars/car_38_4.jpg",
      "uploads/cars/car_38_5.jpg",
      "uploads/cars/car_38_6.jpg",
      "uploads/cars/car_38_7.jpg",
      "uploads/cars/car_38_8.jpg"
    ]
  },
  {
    "id": 39,
    "brand": "Haval",
    "model": "哈弗H6 第三代 1.5T 自动两驱Max",
    "year": 2021,
    "price": 8306,
    "priceLabel": "$8,306",
    "mileage": "45000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_39_39.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_39_39.jpg",
      "uploads/cars/car_39_2.jpg",
      "uploads/cars/car_39_3.jpg",
      "uploads/cars/car_39_4.jpg",
      "uploads/cars/car_39_5.jpg",
      "uploads/cars/car_39_6.jpg",
      "uploads/cars/car_39_7.jpg",
      "uploads/cars/car_39_8.jpg"
    ]
  },
  {
    "id": 40,
    "brand": "Haval",
    "model": "哈弗初恋 1.5T 自动大四版",
    "year": 2021,
    "price": 12333,
    "priceLabel": "$12,333",
    "mileage": "18000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_40_40.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_40_40.jpg",
      "uploads/cars/car_40_2.jpg",
      "uploads/cars/car_40_3.jpg",
      "uploads/cars/car_40_4.jpg",
      "uploads/cars/car_40_5.jpg",
      "uploads/cars/car_40_6.jpg",
      "uploads/cars/car_40_7.jpg",
      "uploads/cars/car_40_8.jpg"
    ]
  },
  {
    "id": 41,
    "brand": "MG",
    "model": "MG5 180DVVT CVT青春豪华版",
    "year": 2021,
    "price": 5528,
    "priceLabel": "$5,528",
    "mileage": "9700 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_41_41.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_41_41.jpg",
      "uploads/cars/car_41_2.jpg",
      "uploads/cars/car_41_3.jpg",
      "uploads/cars/car_41_4.jpg",
      "uploads/cars/car_41_5.jpg",
      "uploads/cars/car_41_6.jpg",
      "uploads/cars/car_41_7.jpg",
      "uploads/cars/car_41_8.jpg"
    ]
  },
  {
    "id": 42,
    "brand": "MG",
    "model": "MG6 Pro 1.5T 自动Trophy豪华版",
    "year": 2021,
    "price": 6431,
    "priceLabel": "$6,431",
    "mileage": "37000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_42_42.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_42_42.jpg",
      "uploads/cars/car_42_2.jpg",
      "uploads/cars/car_42_3.jpg",
      "uploads/cars/car_42_4.jpg",
      "uploads/cars/car_42_5.jpg",
      "uploads/cars/car_42_6.jpg",
      "uploads/cars/car_42_7.jpg",
      "uploads/cars/car_42_8.jpg"
    ]
  },
  {
    "id": 43,
    "brand": "MG",
    "model": "MG7 2.0T 自动猎美尊享版",
    "year": 2023,
    "price": 10944,
    "priceLabel": "$10,944",
    "mileage": "35000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_43_43.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_43_43.jpg",
      "uploads/cars/car_43_2.jpg",
      "uploads/cars/car_43_3.jpg",
      "uploads/cars/car_43_4.jpg",
      "uploads/cars/car_43_5.jpg",
      "uploads/cars/car_43_6.jpg",
      "uploads/cars/car_43_7.jpg",
      "uploads/cars/car_43_8.jpg"
    ]
  },
  {
    "id": 44,
    "brand": "Great Wall",
    "model": "炮 2.0T商用版自动柴油两驱精英型长箱GW4D20M",
    "year": 2023,
    "price": 11083,
    "priceLabel": "$11,083",
    "mileage": "13000 km",
    "fuel_type": "Diesel",
    "transmission": "手动",
    "image": "uploads/cars/car_44_44.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_44_44.jpg",
      "uploads/cars/car_44_2.jpg",
      "uploads/cars/car_44_3.jpg",
      "uploads/cars/car_44_4.jpg",
      "uploads/cars/car_44_5.jpg",
      "uploads/cars/car_44_6.jpg",
      "uploads/cars/car_44_7.jpg",
      "uploads/cars/car_44_8.jpg"
    ]
  },
  {
    "id": 45,
    "brand": "Great Wall",
    "model": "金刚炮 2.0T自动柴油四驱精英型平箱GW4D20M",
    "year": 2023,
    "price": 11917,
    "priceLabel": "$11,917",
    "mileage": "21000 km",
    "fuel_type": "Diesel",
    "transmission": "手动",
    "image": "uploads/cars/car_45_45.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_45_45.jpg",
      "uploads/cars/car_45_2.jpg",
      "uploads/cars/car_45_3.jpg",
      "uploads/cars/car_45_4.jpg",
      "uploads/cars/car_45_5.jpg",
      "uploads/cars/car_45_6.jpg",
      "uploads/cars/car_45_7.jpg",
      "uploads/cars/car_45_8.jpg"
    ]
  },
  {
    "id": 46,
    "brand": "Great Wall",
    "model": "风骏7 2.0T柴油两驱新冠军版公务型大双GW4D20M",
    "year": 2020,
    "price": 7750,
    "priceLabel": "$7,750",
    "mileage": "100000 km",
    "fuel_type": "Diesel",
    "transmission": "手动",
    "image": "uploads/cars/car_46_46.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_46_46.jpg",
      "uploads/cars/car_46_2.jpg",
      "uploads/cars/car_46_3.jpg",
      "uploads/cars/car_46_4.jpg",
      "uploads/cars/car_46_5.jpg",
      "uploads/cars/car_46_6.jpg",
      "uploads/cars/car_46_7.jpg",
      "uploads/cars/car_46_8.jpg"
    ]
  },
  {
    "id": 47,
    "brand": "Roewe",
    "model": "荣威RX5新能源 eRX5 超混优��版",
    "year": 2023,
    "price": 11458,
    "priceLabel": "$11,458",
    "mileage": "100 km",
    "fuel_type": "PHEV",
    "transmission": "自动",
    "image": "uploads/cars/car_47_47.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_47_47.jpg",
      "uploads/cars/car_47_2.jpg",
      "uploads/cars/car_47_3.jpg",
      "uploads/cars/car_47_4.jpg",
      "uploads/cars/car_47_5.jpg",
      "uploads/cars/car_47_6.jpg",
      "uploads/cars/car_47_7.jpg",
      "uploads/cars/car_47_8.jpg"
    ]
  },
  {
    "id": 48,
    "brand": "Roewe",
    "model": "荣威i5 1.5L CVT豪华版",
    "year": 2026,
    "price": 5694,
    "priceLabel": "$5,694",
    "mileage": "8000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_48_48.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_48_48.jpg",
      "uploads/cars/car_48_2.jpg",
      "uploads/cars/car_48_3.jpg",
      "uploads/cars/car_48_4.jpg",
      "uploads/cars/car_48_5.jpg",
      "uploads/cars/car_48_6.jpg",
      "uploads/cars/car_48_7.jpg",
      "uploads/cars/car_48_8.jpg"
    ]
  },
  {
    "id": 49,
    "brand": "Roewe",
    "model": "飞凡F7 进阶版",
    "year": 2023,
    "price": 9583,
    "priceLabel": "$9,583",
    "mileage": "102000 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_49_49.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_49_49.jpg",
      "uploads/cars/car_49_2.jpg",
      "uploads/cars/car_49_3.jpg",
      "uploads/cars/car_49_4.jpg",
      "uploads/cars/car_49_5.jpg",
      "uploads/cars/car_49_6.jpg",
      "uploads/cars/car_49_7.jpg",
      "uploads/cars/car_49_8.jpg"
    ]
  },
  {
    "id": 50,
    "brand": "Jetour",
    "model": "捷途自由者 1.5TD DCT 探索",
    "year": 2025,
    "price": 15944,
    "priceLabel": "$15,944",
    "mileage": "3900 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_50_50.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_50_50.jpg",
      "uploads/cars/car_50_2.jpg",
      "uploads/cars/car_50_3.jpg",
      "uploads/cars/car_50_4.jpg",
      "uploads/cars/car_50_5.jpg",
      "uploads/cars/car_50_6.jpg",
      "uploads/cars/car_50_7.jpg",
      "uploads/cars/car_50_8.jpg"
    ]
  },
  {
    "id": 51,
    "brand": "Jetour",
    "model": "捷途X70 PLUS 冠军版 1.5T DCT冠军MAX+ 5座",
    "year": 2024,
    "price": 10389,
    "priceLabel": "$10,389",
    "mileage": "10000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_51_51.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_51_51.jpg",
      "uploads/cars/car_51_2.jpg",
      "uploads/cars/car_51_3.jpg",
      "uploads/cars/car_51_4.jpg",
      "uploads/cars/car_51_5.jpg",
      "uploads/cars/car_51_6.jpg",
      "uploads/cars/car_51_7.jpg",
      "uploads/cars/car_51_8.jpg"
    ]
  },
  {
    "id": 52,
    "brand": "Avatr",
    "model": "阿维塔06 Pro增程版",
    "year": 2025,
    "price": 20667,
    "priceLabel": "$20,667",
    "mileage": "7400 km",
    "fuel_type": "PHEV",
    "transmission": "自动",
    "image": "uploads/cars/car_52_52.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_52_52.jpg",
      "uploads/cars/car_52_2.jpg",
      "uploads/cars/car_52_3.jpg",
      "uploads/cars/car_52_4.jpg",
      "uploads/cars/car_52_5.jpg",
      "uploads/cars/car_52_6.jpg",
      "uploads/cars/car_52_7.jpg",
      "uploads/cars/car_52_8.jpg"
    ]
  },
  {
    "id": 53,
    "brand": "Avatr",
    "model": "阿维塔07 Max增程版",
    "year": 2024,
    "price": 23583,
    "priceLabel": "$23,583",
    "mileage": "28000 km",
    "fuel_type": "PHEV",
    "transmission": "自动",
    "image": "uploads/cars/car_53_53.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_53_53.jpg",
      "uploads/cars/car_53_2.jpg",
      "uploads/cars/car_53_3.jpg",
      "uploads/cars/car_53_4.jpg",
      "uploads/cars/car_53_5.jpg",
      "uploads/cars/car_53_6.jpg",
      "uploads/cars/car_53_7.jpg",
      "uploads/cars/car_53_8.jpg"
    ]
  },
  {
    "id": 54,
    "brand": "NIO",
    "model": "蔚来EC6 75kWh",
    "year": 2023,
    "price": 29139,
    "priceLabel": "$29,139",
    "mileage": "40000 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_54_54.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_54_54.jpg",
      "uploads/cars/car_54_2.jpg",
      "uploads/cars/car_54_3.jpg",
      "uploads/cars/car_54_4.jpg",
      "uploads/cars/car_54_5.jpg",
      "uploads/cars/car_54_6.jpg",
      "uploads/cars/car_54_7.jpg",
      "uploads/cars/car_54_8.jpg"
    ]
  },
  {
    "id": 55,
    "brand": "NIO",
    "model": "蔚来ET5T 75kWh Touring",
    "year": 2024,
    "price": 20139,
    "priceLabel": "$20,139",
    "mileage": "28000 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_55_55.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_55_55.jpg",
      "uploads/cars/car_55_2.jpg",
      "uploads/cars/car_55_3.jpg",
      "uploads/cars/car_55_4.jpg",
      "uploads/cars/car_55_5.jpg",
      "uploads/cars/car_55_6.jpg",
      "uploads/cars/car_55_7.jpg",
      "uploads/cars/car_55_8.jpg"
    ]
  },
  {
    "id": 56,
    "brand": "XPeng",
    "model": "小鹏G6 625 长续航 Max 科技版",
    "year": 2025,
    "price": 19819,
    "priceLabel": "$19,819",
    "mileage": "13000 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_56_56.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_56_56.jpg",
      "uploads/cars/car_56_2.jpg",
      "uploads/cars/car_56_3.jpg",
      "uploads/cars/car_56_4.jpg",
      "uploads/cars/car_56_5.jpg",
      "uploads/cars/car_56_6.jpg",
      "uploads/cars/car_56_7.jpg",
      "uploads/cars/car_56_8.jpg"
    ]
  },
  {
    "id": 57,
    "brand": "XPeng",
    "model": "小鹏G9 570 Max",
    "year": 2024,
    "price": 26361,
    "priceLabel": "$26,361",
    "mileage": "8000 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_57_57.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_57_57.jpg",
      "uploads/cars/car_57_2.jpg",
      "uploads/cars/car_57_3.jpg",
      "uploads/cars/car_57_4.jpg",
      "uploads/cars/car_57_5.jpg",
      "uploads/cars/car_57_6.jpg",
      "uploads/cars/car_57_7.jpg",
      "uploads/cars/car_57_8.jpg"
    ]
  },
  {
    "id": 58,
    "brand": "Zeekr",
    "model": "极氪007GT 后驱智驾版 75kWh",
    "year": 2025,
    "price": 23028,
    "priceLabel": "$23,028",
    "mileage": "9000 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_58_58.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_58_58.jpg",
      "uploads/cars/car_58_2.jpg",
      "uploads/cars/car_58_3.jpg",
      "uploads/cars/car_58_4.jpg",
      "uploads/cars/car_58_5.jpg",
      "uploads/cars/car_58_6.jpg",
      "uploads/cars/car_58_7.jpg",
      "uploads/cars/car_58_8.jpg"
    ]
  },
  {
    "id": 59,
    "brand": "Zeekr",
    "model": "极氪7X 75kWh 后驱智驾版",
    "year": 2025,
    "price": 22639,
    "priceLabel": "$22,639",
    "mileage": "22400 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_59_59.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_59_59.jpg",
      "uploads/cars/car_59_2.jpg",
      "uploads/cars/car_59_3.jpg",
      "uploads/cars/car_59_4.jpg",
      "uploads/cars/car_59_5.jpg",
      "uploads/cars/car_59_6.jpg",
      "uploads/cars/car_59_7.jpg",
      "uploads/cars/car_59_8.jpg"
    ]
  },
  {
    "id": 60,
    "brand": "BYD",
    "model": "海豹  650智驾版",
    "year": 2025,
    "price": 19833,
    "priceLabel": "$19,833",
    "mileage": "17000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_60_60.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_60_60.jpg",
      "uploads/cars/car_60_2.jpg",
      "uploads/cars/car_60_3.jpg",
      "uploads/cars/car_60_4.jpg",
      "uploads/cars/car_60_5.jpg",
      "uploads/cars/car_60_6.jpg",
      "uploads/cars/car_60_7.jpg",
      "uploads/cars/car_60_8.jpg"
    ]
  },
  {
    "id": 61,
    "brand": "BYD",
    "model": "海豹06  DM-i 智驾版 120KM尊享型",
    "year": 2025,
    "price": 12472,
    "priceLabel": "$12,472",
    "mileage": "7000 km",
    "fuel_type": "PHEV",
    "transmission": "自动",
    "image": "uploads/cars/car_61_61.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_61_61.jpg",
      "uploads/cars/car_61_2.jpg",
      "uploads/cars/car_61_3.jpg",
      "uploads/cars/car_61_4.jpg",
      "uploads/cars/car_61_5.jpg",
      "uploads/cars/car_61_6.jpg",
      "uploads/cars/car_61_7.jpg",
      "uploads/cars/car_61_8.jpg"
    ]
  },
  {
    "id": 62,
    "brand": "BYD",
    "model": "海鸥  305km 活力版",
    "year": 2025,
    "price": 8028,
    "priceLabel": "$8,028",
    "mileage": "100 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_62_62.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_62_62.jpg",
      "uploads/cars/car_62_2.jpg",
      "uploads/cars/car_62_3.jpg",
      "uploads/cars/car_62_4.jpg",
      "uploads/cars/car_62_5.jpg",
      "uploads/cars/car_62_6.jpg",
      "uploads/cars/car_62_7.jpg",
      "uploads/cars/car_62_8.jpg"
    ]
  },
  {
    "id": 63,
    "brand": "BYD",
    "model": "汉  DM-i 智驾版 125KM激光雷达旗舰型",
    "year": 2025,
    "price": 19417,
    "priceLabel": "$19,417",
    "mileage": "2300 km",
    "fuel_type": "PHEV",
    "transmission": "自动",
    "image": "uploads/cars/car_63_63.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_63_63.jpg",
      "uploads/cars/car_63_2.jpg",
      "uploads/cars/car_63_3.jpg",
      "uploads/cars/car_63_4.jpg",
      "uploads/cars/car_63_5.jpg",
      "uploads/cars/car_63_6.jpg",
      "uploads/cars/car_63_7.jpg",
      "uploads/cars/car_63_8.jpg"
    ]
  },
  {
    "id": 64,
    "brand": "BYD",
    "model": "海狮05 EV  520KM旗舰智航版",
    "year": 2025,
    "price": 15000,
    "priceLabel": "$15,000",
    "mileage": "5200 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_64_64.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_64_64.jpg",
      "uploads/cars/car_64_2.jpg",
      "uploads/cars/car_64_3.jpg",
      "uploads/cars/car_64_4.jpg",
      "uploads/cars/car_64_5.jpg",
      "uploads/cars/car_64_6.jpg",
      "uploads/cars/car_64_7.jpg",
      "uploads/cars/car_64_8.jpg"
    ]
  },
  {
    "id": 65,
    "brand": "Chery",
    "model": "艾瑞泽8  1.6T DCT尚",
    "year": 2023,
    "price": 7333,
    "priceLabel": "$7,333",
    "mileage": "36000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_65_65.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_65_65.jpg",
      "uploads/cars/car_65_2.jpg",
      "uploads/cars/car_65_3.jpg",
      "uploads/cars/car_65_4.jpg",
      "uploads/cars/car_65_5.jpg",
      "uploads/cars/car_65_6.jpg",
      "uploads/cars/car_65_7.jpg",
      "uploads/cars/car_65_8.jpg"
    ]
  },
  {
    "id": 66,
    "brand": "Chery",
    "model": "艾瑞泽5  卓越版 1.5L 手动风尚型",
    "year": 2025,
    "price": 6639,
    "priceLabel": "$6,639",
    "mileage": "100 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_66_66.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_66_66.jpg",
      "uploads/cars/car_66_2.jpg",
      "uploads/cars/car_66_3.jpg",
      "uploads/cars/car_66_4.jpg",
      "uploads/cars/car_66_5.jpg",
      "uploads/cars/car_66_6.jpg",
      "uploads/cars/car_66_7.jpg",
      "uploads/cars/car_66_8.jpg"
    ]
  },
  {
    "id": 67,
    "brand": "Chery",
    "model": "艾瑞泽8  高能版 2.0T DCT驰",
    "year": 2024,
    "price": 8722,
    "priceLabel": "$8,722",
    "mileage": "31000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_67_67.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_67_67.jpg",
      "uploads/cars/car_67_2.jpg",
      "uploads/cars/car_67_3.jpg",
      "uploads/cars/car_67_4.jpg",
      "uploads/cars/car_67_5.jpg",
      "uploads/cars/car_67_6.jpg",
      "uploads/cars/car_67_7.jpg",
      "uploads/cars/car_67_8.jpg"
    ]
  },
  {
    "id": 68,
    "brand": "Chery",
    "model": "瑞虎8 PLUS  冠军版 290TGDI DCT豪享版 5座",
    "year": 2024,
    "price": 11917,
    "priceLabel": "$11,917",
    "mileage": "27000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_68_68.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_68_68.jpg",
      "uploads/cars/car_68_2.jpg",
      "uploads/cars/car_68_3.jpg",
      "uploads/cars/car_68_4.jpg",
      "uploads/cars/car_68_5.jpg",
      "uploads/cars/car_68_6.jpg",
      "uploads/cars/car_68_7.jpg",
      "uploads/cars/car_68_8.jpg"
    ]
  },
  {
    "id": 69,
    "brand": "Chery",
    "model": "瑞虎8 PLUS  290TGDI DCT尊贵型",
    "year": 2025,
    "price": 12056,
    "priceLabel": "$12,056",
    "mileage": "12700 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_69_69.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_69_69.jpg",
      "uploads/cars/car_69_2.jpg",
      "uploads/cars/car_69_3.jpg",
      "uploads/cars/car_69_4.jpg",
      "uploads/cars/car_69_5.jpg",
      "uploads/cars/car_69_6.jpg",
      "uploads/cars/car_69_7.jpg",
      "uploads/cars/car_69_8.jpg"
    ]
  },
  {
    "id": 70,
    "brand": "Haval",
    "model": "哈弗猛龙新能源  Hi4 145 穿越版",
    "year": 2024,
    "price": 19931,
    "priceLabel": "$19,931",
    "mileage": "19000 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_70_70.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_70_70.jpg",
      "uploads/cars/car_70_2.jpg",
      "uploads/cars/car_70_3.jpg",
      "uploads/cars/car_70_4.jpg",
      "uploads/cars/car_70_5.jpg",
      "uploads/cars/car_70_6.jpg",
      "uploads/cars/car_70_7.jpg",
      "uploads/cars/car_70_8.jpg"
    ]
  },
  {
    "id": 71,
    "brand": "Haval",
    "model": "哈弗H9  2.0T 汽油四驱精英型 5座",
    "year": 2020,
    "price": 13306,
    "priceLabel": "$13,306",
    "mileage": "84900 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_71_71.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_71_71.jpg",
      "uploads/cars/car_71_2.jpg",
      "uploads/cars/car_71_3.jpg",
      "uploads/cars/car_71_4.jpg",
      "uploads/cars/car_71_5.jpg",
      "uploads/cars/car_71_6.jpg",
      "uploads/cars/car_71_7.jpg",
      "uploads/cars/car_71_8.jpg"
    ]
  },
  {
    "id": 72,
    "brand": "Haval",
    "model": "哈弗枭龙MAX  Hi4 110 Plus 智驾版",
    "year": 2025,
    "price": 16639,
    "priceLabel": "$16,639",
    "mileage": "300 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_72_72.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_72_72.jpg",
      "uploads/cars/car_72_2.jpg",
      "uploads/cars/car_72_3.jpg",
      "uploads/cars/car_72_4.jpg",
      "uploads/cars/car_72_5.jpg",
      "uploads/cars/car_72_6.jpg",
      "uploads/cars/car_72_7.jpg",
      "uploads/cars/car_72_8.jpg"
    ]
  },
  {
    "id": 73,
    "brand": "Haval",
    "model": "哈弗大狗  2.0T DCT中华田园犬版",
    "year": 2026,
    "price": 18028,
    "priceLabel": "$18,028",
    "mileage": "100 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_73_73.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_73_73.jpg",
      "uploads/cars/car_73_2.jpg",
      "uploads/cars/car_73_3.jpg",
      "uploads/cars/car_73_4.jpg",
      "uploads/cars/car_73_5.jpg",
      "uploads/cars/car_73_6.jpg",
      "uploads/cars/car_73_7.jpg",
      "uploads/cars/car_73_8.jpg"
    ]
  },
  {
    "id": 74,
    "brand": "Haval",
    "model": "哈弗大狗 PLUS  2.0T 两驱潮野版Plus",
    "year": 2023,
    "price": 15694,
    "priceLabel": "$15,694",
    "mileage": "13800 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_74_74.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_74_74.jpg",
      "uploads/cars/car_74_2.jpg",
      "uploads/cars/car_74_3.jpg",
      "uploads/cars/car_74_4.jpg",
      "uploads/cars/car_74_5.jpg",
      "uploads/cars/car_74_6.jpg",
      "uploads/cars/car_74_7.jpg",
      "uploads/cars/car_74_8.jpg"
    ]
  },
  {
    "id": 75,
    "brand": "MG",
    "model": "MG6  1.5T 自动领潮风尚版",
    "year": 2020,
    "price": 4444,
    "priceLabel": "$4,444",
    "mileage": "26000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_75_75.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_75_75.jpg",
      "uploads/cars/car_75_2.jpg",
      "uploads/cars/car_75_3.jpg",
      "uploads/cars/car_75_4.jpg",
      "uploads/cars/car_75_5.jpg",
      "uploads/cars/car_75_6.jpg",
      "uploads/cars/car_75_7.jpg",
      "uploads/cars/car_75_8.jpg"
    ]
  },
  {
    "id": 76,
    "brand": "MG",
    "model": "MG5  300TGI DCT青奢风潮版",
    "year": 2021,
    "price": 5528,
    "priceLabel": "$5,528",
    "mileage": "49700 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_76_76.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_76_76.jpg",
      "uploads/cars/car_76_2.jpg",
      "uploads/cars/car_76_3.jpg",
      "uploads/cars/car_76_4.jpg",
      "uploads/cars/car_76_5.jpg",
      "uploads/cars/car_76_6.jpg",
      "uploads/cars/car_76_7.jpg",
      "uploads/cars/car_76_8.jpg"
    ]
  },
  {
    "id": 77,
    "brand": "MG",
    "model": "MG7  1.5T DCT至美舒享版",
    "year": 2023,
    "price": 7611,
    "priceLabel": "$7,611",
    "mileage": "53000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_77_77.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_77_77.jpg",
      "uploads/cars/car_77_2.jpg",
      "uploads/cars/car_77_3.jpg",
      "uploads/cars/car_77_4.jpg",
      "uploads/cars/car_77_5.jpg",
      "uploads/cars/car_77_6.jpg",
      "uploads/cars/car_77_7.jpg",
      "uploads/cars/car_77_8.jpg"
    ]
  },
  {
    "id": 78,
    "brand": "MG",
    "model": "MG5  180DVVT CVT青春风尚版",
    "year": 2022,
    "price": 5111,
    "priceLabel": "$5,111",
    "mileage": "25000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_78_78.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_78_78.jpg",
      "uploads/cars/car_78_2.jpg",
      "uploads/cars/car_78_3.jpg",
      "uploads/cars/car_78_4.jpg",
      "uploads/cars/car_78_5.jpg",
      "uploads/cars/car_78_6.jpg",
      "uploads/cars/car_78_7.jpg",
      "uploads/cars/car_78_8.jpg"
    ]
  },
  {
    "id": 79,
    "brand": "MG",
    "model": "MG7  2.0T 自动Trophy+激擎耀世版",
    "year": 2023,
    "price": 12667,
    "priceLabel": "$12,667",
    "mileage": "22000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_79_79.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_79_79.jpg",
      "uploads/cars/car_79_2.jpg",
      "uploads/cars/car_79_3.jpg",
      "uploads/cars/car_79_4.jpg",
      "uploads/cars/car_79_5.jpg",
      "uploads/cars/car_79_6.jpg",
      "uploads/cars/car_79_7.jpg",
      "uploads/cars/car_79_8.jpg"
    ]
  },
  {
    "id": 80,
    "brand": "Great Wall",
    "model": "炮  2.0T商用版自动柴油两驱领航型长箱GW4D20M",
    "year": 2021,
    "price": 10264,
    "priceLabel": "$10,264",
    "mileage": "50000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_80_80.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_80_80.jpg",
      "uploads/cars/car_80_2.jpg",
      "uploads/cars/car_80_3.jpg",
      "uploads/cars/car_80_4.jpg",
      "uploads/cars/car_80_5.jpg",
      "uploads/cars/car_80_6.jpg",
      "uploads/cars/car_80_7.jpg",
      "uploads/cars/car_80_8.jpg"
    ]
  },
  {
    "id": 81,
    "brand": "Great Wall",
    "model": "风骏7  2.0T柴油两驱精英型国VI大双GW4D20M",
    "year": 2019,
    "price": 7222,
    "priceLabel": "$7,222",
    "mileage": "70000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_81_81.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_81_81.jpg",
      "uploads/cars/car_81_2.jpg",
      "uploads/cars/car_81_3.jpg",
      "uploads/cars/car_81_4.jpg",
      "uploads/cars/car_81_5.jpg",
      "uploads/cars/car_81_6.jpg",
      "uploads/cars/car_81_7.jpg",
      "uploads/cars/car_81_8.jpg"
    ]
  },
  {
    "id": 82,
    "brand": "Great Wall",
    "model": "炮  2.4T商用版自动柴油四驱精英型",
    "year": 2024,
    "price": 14833,
    "priceLabel": "$14,833",
    "mileage": "26000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_82_82.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_82_82.jpg",
      "uploads/cars/car_82_2.jpg",
      "uploads/cars/car_82_3.jpg",
      "uploads/cars/car_82_4.jpg",
      "uploads/cars/car_82_5.jpg",
      "uploads/cars/car_82_6.jpg",
      "uploads/cars/car_82_7.jpg",
      "uploads/cars/car_82_8.jpg"
    ]
  },
  {
    "id": 83,
    "brand": "Great Wall",
    "model": "炮  2.0T商用版 自动柴油四驱茶王版长箱GW4D20M",
    "year": 2021,
    "price": 13861,
    "priceLabel": "$13,861",
    "mileage": "71000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_83_83.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_83_83.jpg",
      "uploads/cars/car_83_2.jpg",
      "uploads/cars/car_83_3.jpg",
      "uploads/cars/car_83_4.jpg",
      "uploads/cars/car_83_5.jpg",
      "uploads/cars/car_83_6.jpg",
      "uploads/cars/car_83_7.jpg",
      "uploads/cars/car_83_8.jpg"
    ]
  },
  {
    "id": 84,
    "brand": "Great Wall",
    "model": "炮  2.0T商用版手动柴油两驱精英型长箱GW4D20M",
    "year": 2019,
    "price": 7764,
    "priceLabel": "$7,764",
    "mileage": "36100 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_84_84.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_84_84.jpg",
      "uploads/cars/car_84_2.jpg",
      "uploads/cars/car_84_3.jpg",
      "uploads/cars/car_84_4.jpg",
      "uploads/cars/car_84_5.jpg",
      "uploads/cars/car_84_6.jpg",
      "uploads/cars/car_84_7.jpg",
      "uploads/cars/car_84_8.jpg"
    ]
  },
  {
    "id": 85,
    "brand": "Avatr",
    "model": "阿维塔06  Pro纯电版",
    "year": 2025,
    "price": 28319,
    "priceLabel": "$28,319",
    "mileage": "100 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_85_85.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_85_85.jpg",
      "uploads/cars/car_85_2.jpg",
      "uploads/cars/car_85_3.jpg",
      "uploads/cars/car_85_4.jpg",
      "uploads/cars/car_85_5.jpg",
      "uploads/cars/car_85_6.jpg",
      "uploads/cars/car_85_7.jpg",
      "uploads/cars/car_85_8.jpg"
    ]
  },
  {
    "id": 86,
    "brand": "Avatr",
    "model": "阿维塔11  Max 增程版",
    "year": 2025,
    "price": 29972,
    "priceLabel": "$29,972",
    "mileage": "800 km",
    "fuel_type": "PHEV",
    "transmission": "自动",
    "image": "uploads/cars/car_86_86.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_86_86.jpg",
      "uploads/cars/car_86_2.jpg",
      "uploads/cars/car_86_3.jpg",
      "uploads/cars/car_86_4.jpg",
      "uploads/cars/car_86_5.jpg",
      "uploads/cars/car_86_6.jpg",
      "uploads/cars/car_86_7.jpg",
      "uploads/cars/car_86_8.jpg"
    ]
  },
  {
    "id": 87,
    "brand": "Avatr",
    "model": "阿维塔06  Ultra纯电版",
    "year": 2025,
    "price": 25972,
    "priceLabel": "$25,972",
    "mileage": "16000 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_87_87.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_87_87.jpg",
      "uploads/cars/car_87_2.jpg",
      "uploads/cars/car_87_3.jpg",
      "uploads/cars/car_87_4.jpg",
      "uploads/cars/car_87_5.jpg",
      "uploads/cars/car_87_6.jpg",
      "uploads/cars/car_87_7.jpg",
      "uploads/cars/car_87_8.jpg"
    ]
  },
  {
    "id": 88,
    "brand": "Avatr",
    "model": "阿维塔06  Max纯电版",
    "year": 2025,
    "price": 28319,
    "priceLabel": "$28,319",
    "mileage": "100 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_88_88.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_88_88.jpg",
      "uploads/cars/car_88_2.jpg",
      "uploads/cars/car_88_3.jpg",
      "uploads/cars/car_88_4.jpg",
      "uploads/cars/car_88_5.jpg",
      "uploads/cars/car_88_6.jpg",
      "uploads/cars/car_88_7.jpg",
      "uploads/cars/car_88_8.jpg"
    ]
  },
  {
    "id": 89,
    "brand": "Avatr",
    "model": "阿维塔12  改款 Ultra增程版",
    "year": 2025,
    "price": 30000,
    "priceLabel": "$30,000",
    "mileage": "8600 km",
    "fuel_type": "PHEV",
    "transmission": "自动",
    "image": "uploads/cars/car_89_89.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_89_89.jpg",
      "uploads/cars/car_89_2.jpg",
      "uploads/cars/car_89_3.jpg",
      "uploads/cars/car_89_4.jpg",
      "uploads/cars/car_89_5.jpg",
      "uploads/cars/car_89_6.jpg",
      "uploads/cars/car_89_7.jpg",
      "uploads/cars/car_89_8.jpg"
    ]
  },
  {
    "id": 90,
    "brand": "NIO",
    "model": "蔚来ES8  六座行政豪华版",
    "year": 2026,
    "price": 48583,
    "priceLabel": "$48,583",
    "mileage": "1000 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_90_90.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_90_90.jpg",
      "uploads/cars/car_90_2.jpg",
      "uploads/cars/car_90_3.jpg",
      "uploads/cars/car_90_4.jpg",
      "uploads/cars/car_90_5.jpg",
      "uploads/cars/car_90_6.jpg",
      "uploads/cars/car_90_7.jpg",
      "uploads/cars/car_90_8.jpg"
    ]
  },
  {
    "id": 91,
    "brand": "NIO",
    "model": "蔚来ES6  430KM 性能版",
    "year": 2020,
    "price": 15250,
    "priceLabel": "$15,250",
    "mileage": "90000 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_91_91.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_91_91.jpg",
      "uploads/cars/car_91_2.jpg",
      "uploads/cars/car_91_3.jpg",
      "uploads/cars/car_91_4.jpg",
      "uploads/cars/car_91_5.jpg",
      "uploads/cars/car_91_6.jpg",
      "uploads/cars/car_91_7.jpg",
      "uploads/cars/car_91_8.jpg"
    ]
  },
  {
    "id": 92,
    "brand": "NIO",
    "model": "蔚来EC6  75kWh",
    "year": 2023,
    "price": 21528,
    "priceLabel": "$21,528",
    "mileage": "50000 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_92_92.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_92_92.jpg",
      "uploads/cars/car_92_2.jpg",
      "uploads/cars/car_92_3.jpg",
      "uploads/cars/car_92_4.jpg",
      "uploads/cars/car_92_5.jpg",
      "uploads/cars/car_92_6.jpg",
      "uploads/cars/car_92_7.jpg",
      "uploads/cars/car_92_8.jpg"
    ]
  },
  {
    "id": 93,
    "brand": "NIO",
    "model": "蔚来ES8  415KM 签名版 六座版",
    "year": 2020,
    "price": 15250,
    "priceLabel": "$15,250",
    "mileage": "109000 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_93_93.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_93_93.jpg",
      "uploads/cars/car_93_2.jpg",
      "uploads/cars/car_93_3.jpg",
      "uploads/cars/car_93_4.jpg",
      "uploads/cars/car_93_5.jpg",
      "uploads/cars/car_93_6.jpg",
      "uploads/cars/car_93_7.jpg",
      "uploads/cars/car_93_8.jpg"
    ]
  },
  {
    "id": 94,
    "brand": "XPeng",
    "model": "小鹏P7  702 长续航 Ultra",
    "year": 2025,
    "price": 22750,
    "priceLabel": "$22,750",
    "mileage": "8900 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_94_94.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_94_94.jpg",
      "uploads/cars/car_94_2.jpg",
      "uploads/cars/car_94_3.jpg",
      "uploads/cars/car_94_4.jpg",
      "uploads/cars/car_94_5.jpg",
      "uploads/cars/car_94_6.jpg",
      "uploads/cars/car_94_7.jpg",
      "uploads/cars/car_94_8.jpg"
    ]
  },
  {
    "id": 95,
    "brand": "XPeng",
    "model": "小鹏G7  702 超长续航 Ultra",
    "year": 2025,
    "price": 24153,
    "priceLabel": "$24,153",
    "mileage": "10600 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_95_95.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_95_95.jpg",
      "uploads/cars/car_95_2.jpg",
      "uploads/cars/car_95_3.jpg",
      "uploads/cars/car_95_4.jpg",
      "uploads/cars/car_95_5.jpg",
      "uploads/cars/car_95_6.jpg",
      "uploads/cars/car_95_7.jpg",
      "uploads/cars/car_95_8.jpg"
    ]
  },
  {
    "id": 96,
    "brand": "XPeng",
    "model": "小鹏X9  纯电 740超长续航 Max",
    "year": 2025,
    "price": 36528,
    "priceLabel": "$36,528",
    "mileage": "9400 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_96_96.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_96_96.jpg",
      "uploads/cars/car_96_2.jpg",
      "uploads/cars/car_96_3.jpg",
      "uploads/cars/car_96_4.jpg",
      "uploads/cars/car_96_5.jpg",
      "uploads/cars/car_96_6.jpg",
      "uploads/cars/car_96_7.jpg",
      "uploads/cars/car_96_8.jpg"
    ]
  },
  {
    "id": 97,
    "brand": "XPeng",
    "model": "小鹏X9  纯电 650长续航 Max",
    "year": 2025,
    "price": 35667,
    "priceLabel": "$35,667",
    "mileage": "7900 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_97_97.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_97_97.jpg",
      "uploads/cars/car_97_2.jpg",
      "uploads/cars/car_97_3.jpg",
      "uploads/cars/car_97_4.jpg",
      "uploads/cars/car_97_5.jpg",
      "uploads/cars/car_97_6.jpg",
      "uploads/cars/car_97_7.jpg",
      "uploads/cars/car_97_8.jpg"
    ]
  },
  {
    "id": 98,
    "brand": "Zeekr",
    "model": "极氪009  七座过道版四驱 108kWh",
    "year": 2024,
    "price": 51361,
    "priceLabel": "$51,361",
    "mileage": "8000 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_98_98.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_98_98.jpg",
      "uploads/cars/car_98_2.jpg",
      "uploads/cars/car_98_3.jpg",
      "uploads/cars/car_98_4.jpg",
      "uploads/cars/car_98_5.jpg",
      "uploads/cars/car_98_6.jpg",
      "uploads/cars/car_98_7.jpg",
      "uploads/cars/car_98_8.jpg"
    ]
  },
  {
    "id": 99,
    "brand": "Zeekr",
    "model": "极氪009  六座行政版四驱 108kWh",
    "year": 2024,
    "price": 53750,
    "priceLabel": "$53,750",
    "mileage": "5900 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_99_99.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_99_99.jpg",
      "uploads/cars/car_99_2.jpg",
      "uploads/cars/car_99_3.jpg",
      "uploads/cars/car_99_4.jpg",
      "uploads/cars/car_99_5.jpg",
      "uploads/cars/car_99_6.jpg",
      "uploads/cars/car_99_7.jpg",
      "uploads/cars/car_99_8.jpg"
    ]
  },
  {
    "id": 100,
    "brand": "Zeekr",
    "model": "极氪7X  100kWh 长续航四驱智驾版",
    "year": 2025,
    "price": 24972,
    "priceLabel": "$24,972",
    "mileage": "10000 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_100_100.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_100_100.jpg",
      "uploads/cars/car_100_2.jpg",
      "uploads/cars/car_100_3.jpg",
      "uploads/cars/car_100_4.jpg",
      "uploads/cars/car_100_5.jpg",
      "uploads/cars/car_100_6.jpg",
      "uploads/cars/car_100_7.jpg",
      "uploads/cars/car_100_8.jpg"
    ]
  },
  {
    "id": 101,
    "brand": "Zeekr",
    "model": "极氪001  长续航双电机 WE版",
    "year": 2021,
    "price": 21528,
    "priceLabel": "$21,528",
    "mileage": "68000 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_101_101.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_101_101.jpg",
      "uploads/cars/car_101_2.jpg",
      "uploads/cars/car_101_3.jpg",
      "uploads/cars/car_101_4.jpg",
      "uploads/cars/car_101_5.jpg",
      "uploads/cars/car_101_6.jpg",
      "uploads/cars/car_101_7.jpg",
      "uploads/cars/car_101_8.jpg"
    ]
  },
  {
    "id": 102,
    "brand": "Roewe",
    "model": "飞凡R7  长续Pro版",
    "year": 2024,
    "price": 10736,
    "priceLabel": "$10,736",
    "mileage": "28000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_102_102.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_102_102.jpg",
      "uploads/cars/car_102_2.jpg",
      "uploads/cars/car_102_3.jpg",
      "uploads/cars/car_102_4.jpg",
      "uploads/cars/car_102_5.jpg",
      "uploads/cars/car_102_6.jpg",
      "uploads/cars/car_102_7.jpg",
      "uploads/cars/car_102_8.jpg"
    ]
  },
  {
    "id": 103,
    "brand": "Roewe",
    "model": "荣威RX5  1.5T 超感精英版",
    "year": 2023,
    "price": 5764,
    "priceLabel": "$5,764",
    "mileage": "30000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_103_103.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_103_103.jpg",
      "uploads/cars/car_103_2.jpg",
      "uploads/cars/car_103_3.jpg",
      "uploads/cars/car_103_4.jpg",
      "uploads/cars/car_103_5.jpg",
      "uploads/cars/car_103_6.jpg",
      "uploads/cars/car_103_7.jpg",
      "uploads/cars/car_103_8.jpg"
    ]
  },
  {
    "id": 104,
    "brand": "Roewe",
    "model": "荣威RX5新能源  eRX5 超混优越版",
    "year": 2023,
    "price": 11458,
    "priceLabel": "$11,458",
    "mileage": "100 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_104_104.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_104_104.jpg",
      "uploads/cars/car_104_2.jpg",
      "uploads/cars/car_104_3.jpg",
      "uploads/cars/car_104_4.jpg",
      "uploads/cars/car_104_5.jpg",
      "uploads/cars/car_104_6.jpg",
      "uploads/cars/car_104_7.jpg",
      "uploads/cars/car_104_8.jpg"
    ]
  },
  {
    "id": 105,
    "brand": "Roewe",
    "model": "荣威iMAX8  400TGI 尊荣版",
    "year": 2022,
    "price": 12750,
    "priceLabel": "$12,750",
    "mileage": "20000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_105_105.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_105_105.jpg",
      "uploads/cars/car_105_2.jpg",
      "uploads/cars/car_105_3.jpg",
      "uploads/cars/car_105_4.jpg",
      "uploads/cars/car_105_5.jpg",
      "uploads/cars/car_105_6.jpg",
      "uploads/cars/car_105_7.jpg",
      "uploads/cars/car_105_8.jpg"
    ]
  },
  {
    "id": 106,
    "brand": "Jetour",
    "model": "捷途X70  1.5T DCT跃享版 5座",
    "year": 2024,
    "price": 11653,
    "priceLabel": "$11,653",
    "mileage": "18000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_106_106.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_106_106.jpg",
      "uploads/cars/car_106_2.jpg",
      "uploads/cars/car_106_3.jpg",
      "uploads/cars/car_106_4.jpg",
      "uploads/cars/car_106_5.jpg",
      "uploads/cars/car_106_6.jpg",
      "uploads/cars/car_106_7.jpg",
      "uploads/cars/car_106_8.jpg"
    ]
  },
  {
    "id": 107,
    "brand": "Jetour",
    "model": "捷途X70 PLUS  改款 1.5T DCT山PRO 5座",
    "year": 2021,
    "price": 8194,
    "priceLabel": "$8,194",
    "mileage": "32000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_107_107.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_107_107.jpg",
      "uploads/cars/car_107_2.jpg",
      "uploads/cars/car_107_3.jpg",
      "uploads/cars/car_107_4.jpg",
      "uploads/cars/car_107_5.jpg",
      "uploads/cars/car_107_6.jpg",
      "uploads/cars/car_107_7.jpg",
      "uploads/cars/car_107_8.jpg"
    ]
  },
  {
    "id": 108,
    "brand": "Jetour",
    "model": "捷途旅行者  1.5T 两驱发现PRO",
    "year": 2023,
    "price": 16361,
    "priceLabel": "$16,361",
    "mileage": "16500 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_108_108.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_108_108.jpg",
      "uploads/cars/car_108_2.jpg",
      "uploads/cars/car_108_3.jpg",
      "uploads/cars/car_108_4.jpg",
      "uploads/cars/car_108_5.jpg",
      "uploads/cars/car_108_6.jpg",
      "uploads/cars/car_108_7.jpg",
      "uploads/cars/car_108_8.jpg"
    ]
  },
  {
    "id": 109,
    "brand": "Jetour",
    "model": "捷途自由者  1.5TD DCT 探索",
    "year": 2025,
    "price": 15944,
    "priceLabel": "$15,944",
    "mileage": "6600 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_109_109.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_109_109.jpg",
      "uploads/cars/car_109_2.jpg",
      "uploads/cars/car_109_3.jpg",
      "uploads/cars/car_109_4.jpg",
      "uploads/cars/car_109_5.jpg",
      "uploads/cars/car_109_6.jpg",
      "uploads/cars/car_109_7.jpg",
      "uploads/cars/car_109_8.jpg"
    ]
  },
  {
    "id": 110,
    "brand": "Toyota",
    "model": "Corolla 1.2T 先锋版",
    "year": 2023,
    "price": 11200,
    "priceLabel": "$11,200",
    "mileage": "32000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_110_110.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_110_110.jpg",
      "uploads/cars/car_110_2.jpg",
      "uploads/cars/car_110_3.jpg",
      "uploads/cars/car_110_4.jpg",
      "uploads/cars/car_110_5.jpg",
      "uploads/cars/car_110_6.jpg",
      "uploads/cars/car_110_7.jpg",
      "uploads/cars/car_110_8.jpg"
    ]
  },
  {
    "id": 111,
    "brand": "Toyota",
    "model": "Camry 2.0E 精英版",
    "year": 2022,
    "price": 15200,
    "priceLabel": "$15,200",
    "mileage": "45000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_111_111.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_111_111.jpg",
      "uploads/cars/car_111_2.jpg",
      "uploads/cars/car_111_3.jpg",
      "uploads/cars/car_111_4.jpg",
      "uploads/cars/car_111_5.jpg",
      "uploads/cars/car_111_6.jpg",
      "uploads/cars/car_111_7.jpg",
      "uploads/cars/car_111_8.jpg"
    ]
  },
  {
    "id": 112,
    "brand": "Toyota",
    "model": "RAV4 2.0L CVT两驱都市版",
    "year": 2023,
    "price": 17800,
    "priceLabel": "$17,800",
    "mileage": "25000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_112_112.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_112_112.jpg",
      "uploads/cars/car_112_2.jpg",
      "uploads/cars/car_112_3.jpg",
      "uploads/cars/car_112_4.jpg",
      "uploads/cars/car_112_5.jpg",
      "uploads/cars/car_112_6.jpg",
      "uploads/cars/car_112_7.jpg",
      "uploads/cars/car_112_8.jpg"
    ]
  },
  {
    "id": 113,
    "brand": "Toyota",
    "model": "Land Cruiser Prado 2.7L",
    "year": 2021,
    "price": 35800,
    "priceLabel": "$35,800",
    "mileage": "58000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_113_113.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_113_113.jpg",
      "uploads/cars/car_113_2.jpg",
      "uploads/cars/car_113_3.jpg",
      "uploads/cars/car_113_4.jpg",
      "uploads/cars/car_113_5.jpg",
      "uploads/cars/car_113_6.jpg",
      "uploads/cars/car_113_7.jpg",
      "uploads/cars/car_113_8.jpg"
    ]
  },
  {
    "id": 114,
    "brand": "Toyota",
    "model": "Hilux 2.7L 双排皮卡",
    "year": 2022,
    "price": 22800,
    "priceLabel": "$22,800",
    "mileage": "40000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_114_114.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_114_114.jpg",
      "uploads/cars/car_114_2.jpg",
      "uploads/cars/car_114_3.jpg",
      "uploads/cars/car_114_4.jpg",
      "uploads/cars/car_114_5.jpg",
      "uploads/cars/car_114_6.jpg",
      "uploads/cars/car_114_7.jpg",
      "uploads/cars/car_114_8.jpg"
    ]
  },
  {
    "id": 115,
    "brand": "Toyota",
    "model": "Fortuner 2.7L TRD",
    "year": 2023,
    "price": 26800,
    "priceLabel": "$26,800",
    "mileage": "15000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_115_115.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_115_115.jpg",
      "uploads/cars/car_115_2.jpg",
      "uploads/cars/car_115_3.jpg",
      "uploads/cars/car_115_4.jpg",
      "uploads/cars/car_115_5.jpg",
      "uploads/cars/car_115_6.jpg",
      "uploads/cars/car_115_7.jpg",
      "uploads/cars/car_115_8.jpg"
    ]
  },
  {
    "id": 116,
    "brand": "Toyota",
    "model": "Yaris 1.5L CVT 领先版",
    "year": 2022,
    "price": 7200,
    "priceLabel": "$7,200",
    "mileage": "35000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_116_116.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_116_116.jpg",
      "uploads/cars/car_116_2.jpg",
      "uploads/cars/car_116_3.jpg",
      "uploads/cars/car_116_4.jpg",
      "uploads/cars/car_116_5.jpg",
      "uploads/cars/car_116_6.jpg",
      "uploads/cars/car_116_7.jpg",
      "uploads/cars/car_116_8.jpg"
    ]
  },
  {
    "id": 117,
    "brand": "Toyota",
    "model": "Vios 1.5L CVT 智行版",
    "year": 2023,
    "price": 8300,
    "priceLabel": "$8,300",
    "mileage": "20000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_117_117.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_117_117.jpg",
      "uploads/cars/car_117_2.jpg",
      "uploads/cars/car_117_3.jpg",
      "uploads/cars/car_117_4.jpg",
      "uploads/cars/car_117_5.jpg",
      "uploads/cars/car_117_6.jpg",
      "uploads/cars/car_117_7.jpg",
      "uploads/cars/car_117_8.jpg"
    ]
  },
  {
    "id": 118,
    "brand": "Toyota",
    "model": "Innova 2.0L 7座MPV",
    "year": 2021,
    "price": 12600,
    "priceLabel": "$12,600",
    "mileage": "48000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_118_118.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_118_118.jpg",
      "uploads/cars/car_118_2.jpg",
      "uploads/cars/car_118_3.jpg",
      "uploads/cars/car_118_4.jpg",
      "uploads/cars/car_118_5.jpg",
      "uploads/cars/car_118_6.jpg",
      "uploads/cars/car_118_7.jpg",
      "uploads/cars/car_118_8.jpg"
    ]
  },
  {
    "id": 119,
    "brand": "Toyota",
    "model": "Alphard 3.5L 豪华版",
    "year": 2020,
    "price": 39800,
    "priceLabel": "$39,800",
    "mileage": "62000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_119_119.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_119_119.jpg",
      "uploads/cars/car_119_2.jpg",
      "uploads/cars/car_119_3.jpg",
      "uploads/cars/car_119_4.jpg",
      "uploads/cars/car_119_5.jpg",
      "uploads/cars/car_119_6.jpg",
      "uploads/cars/car_119_7.jpg",
      "uploads/cars/car_119_8.jpg"
    ]
  },
  {
    "id": 120,
    "brand": "Toyota",
    "model": "Hiace 2.7L 12座 商务车",
    "year": 2022,
    "price": 19800,
    "priceLabel": "$19,800",
    "mileage": "36000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_120_120.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_120_120.jpg",
      "uploads/cars/car_120_2.jpg",
      "uploads/cars/car_120_3.jpg",
      "uploads/cars/car_120_4.jpg",
      "uploads/cars/car_120_5.jpg",
      "uploads/cars/car_120_6.jpg",
      "uploads/cars/car_120_7.jpg",
      "uploads/cars/car_120_8.jpg"
    ]
  },
  {
    "id": 121,
    "brand": "Toyota",
    "model": "C-HR 2.0L CVT 领先版",
    "year": 2023,
    "price": 13500,
    "priceLabel": "$13,500",
    "mileage": "18000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_121_121.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_121_121.jpg",
      "uploads/cars/car_121_2.jpg",
      "uploads/cars/car_121_3.jpg",
      "uploads/cars/car_121_4.jpg",
      "uploads/cars/car_121_5.jpg",
      "uploads/cars/car_121_6.jpg",
      "uploads/cars/car_121_7.jpg",
      "uploads/cars/car_121_8.jpg"
    ]
  },
  {
    "id": 122,
    "brand": "Toyota",
    "model": "Corolla Cross 1.8L 精英版",
    "year": 2023,
    "price": 14800,
    "priceLabel": "$14,800",
    "mileage": "22000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_122_122.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_122_122.jpg",
      "uploads/cars/car_122_2.jpg",
      "uploads/cars/car_122_3.jpg",
      "uploads/cars/car_122_4.jpg",
      "uploads/cars/car_122_5.jpg",
      "uploads/cars/car_122_6.jpg",
      "uploads/cars/car_122_7.jpg",
      "uploads/cars/car_122_8.jpg"
    ]
  },
  {
    "id": 123,
    "brand": "Toyota",
    "model": "Highlander 2.0T 四驱尊贵版",
    "year": 2022,
    "price": 27800,
    "priceLabel": "$27,800",
    "mileage": "34000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_123_123.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_123_123.jpg",
      "uploads/cars/car_123_2.jpg",
      "uploads/cars/car_123_3.jpg",
      "uploads/cars/car_123_4.jpg",
      "uploads/cars/car_123_5.jpg",
      "uploads/cars/car_123_6.jpg",
      "uploads/cars/car_123_7.jpg",
      "uploads/cars/car_123_8.jpg"
    ]
  },
  {
    "id": 124,
    "brand": "Toyota",
    "model": "Harrier 2.0L CVT 两驱豪华版",
    "year": 2023,
    "price": 20500,
    "priceLabel": "$20,500",
    "mileage": "16000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_124_124.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_124_124.jpg",
      "uploads/cars/car_124_2.jpg",
      "uploads/cars/car_124_3.jpg",
      "uploads/cars/car_124_4.jpg",
      "uploads/cars/car_124_5.jpg",
      "uploads/cars/car_124_6.jpg",
      "uploads/cars/car_124_7.jpg",
      "uploads/cars/car_124_8.jpg"
    ]
  },
  {
    "id": 125,
    "brand": "Volkswagen",
    "model": "Passat 330TSI 精英版",
    "year": 2022,
    "price": 13800,
    "priceLabel": "$13,800",
    "mileage": "42000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_125_125.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_125_125.jpg",
      "uploads/cars/car_125_2.jpg",
      "uploads/cars/car_125_3.jpg",
      "uploads/cars/car_125_4.jpg",
      "uploads/cars/car_125_5.jpg",
      "uploads/cars/car_125_6.jpg",
      "uploads/cars/car_125_7.jpg",
      "uploads/cars/car_125_8.jpg"
    ]
  },
  {
    "id": 126,
    "brand": "Volkswagen",
    "model": "Tiguan 330TSI 两驱智享版",
    "year": 2023,
    "price": 16800,
    "priceLabel": "$16,800",
    "mileage": "28000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_126_126.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_126_126.jpg",
      "uploads/cars/car_126_2.jpg",
      "uploads/cars/car_126_3.jpg",
      "uploads/cars/car_126_4.jpg",
      "uploads/cars/car_126_5.jpg",
      "uploads/cars/car_126_6.jpg",
      "uploads/cars/car_126_7.jpg",
      "uploads/cars/car_126_8.jpg"
    ]
  },
  {
    "id": 127,
    "brand": "Volkswagen",
    "model": "Polo 1.5L 自动全景乐享版",
    "year": 2022,
    "price": 6800,
    "priceLabel": "$6,800",
    "mileage": "38000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_127_127.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_127_127.jpg",
      "uploads/cars/car_127_2.jpg",
      "uploads/cars/car_127_3.jpg",
      "uploads/cars/car_127_4.jpg",
      "uploads/cars/car_127_5.jpg",
      "uploads/cars/car_127_6.jpg",
      "uploads/cars/car_127_7.jpg",
      "uploads/cars/car_127_8.jpg"
    ]
  },
  {
    "id": 128,
    "brand": "Volkswagen",
    "model": "Lavida 1.5L 自动舒适版",
    "year": 2023,
    "price": 9200,
    "priceLabel": "$9,200",
    "mileage": "24000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_128_128.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_128_128.jpg",
      "uploads/cars/car_128_2.jpg",
      "uploads/cars/car_128_3.jpg",
      "uploads/cars/car_128_4.jpg",
      "uploads/cars/car_128_5.jpg",
      "uploads/cars/car_128_6.jpg",
      "uploads/cars/car_128_7.jpg",
      "uploads/cars/car_128_8.jpg"
    ]
  },
  {
    "id": 129,
    "brand": "Volkswagen",
    "model": "Magotan 330TSI DSG 豪华版",
    "year": 2022,
    "price": 16200,
    "priceLabel": "$16,200",
    "mileage": "36000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_129_129.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_129_129.jpg",
      "uploads/cars/car_129_2.jpg",
      "uploads/cars/car_129_3.jpg",
      "uploads/cars/car_129_4.jpg",
      "uploads/cars/car_129_5.jpg",
      "uploads/cars/car_129_6.jpg",
      "uploads/cars/car_129_7.jpg",
      "uploads/cars/car_129_8.jpg"
    ]
  },
  {
    "id": 130,
    "brand": "Volkswagen",
    "model": "T-Roc 280TSI 两驱豪华版",
    "year": 2023,
    "price": 12800,
    "priceLabel": "$12,800",
    "mileage": "20000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_130_130.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_130_130.jpg",
      "uploads/cars/car_130_2.jpg",
      "uploads/cars/car_130_3.jpg",
      "uploads/cars/car_130_4.jpg",
      "uploads/cars/car_130_5.jpg",
      "uploads/cars/car_130_6.jpg",
      "uploads/cars/car_130_7.jpg",
      "uploads/cars/car_130_8.jpg"
    ]
  },
  {
    "id": 131,
    "brand": "Volkswagen",
    "model": "Tayron 330TSI 两驱豪华版",
    "year": 2023,
    "price": 15800,
    "priceLabel": "$15,800",
    "mileage": "26000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_131_131.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_131_131.jpg",
      "uploads/cars/car_131_2.jpg",
      "uploads/cars/car_131_3.jpg",
      "uploads/cars/car_131_4.jpg",
      "uploads/cars/car_131_5.jpg",
      "uploads/cars/car_131_6.jpg",
      "uploads/cars/car_131_7.jpg",
      "uploads/cars/car_131_8.jpg"
    ]
  },
  {
    "id": 132,
    "brand": "Volkswagen",
    "model": "Tharu 280TSI 两驱舒适版",
    "year": 2022,
    "price": 11800,
    "priceLabel": "$11,800",
    "mileage": "30000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_132_132.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_132_132.jpg",
      "uploads/cars/car_132_2.jpg",
      "uploads/cars/car_132_3.jpg",
      "uploads/cars/car_132_4.jpg",
      "uploads/cars/car_132_5.jpg",
      "uploads/cars/car_132_6.jpg",
      "uploads/cars/car_132_7.jpg",
      "uploads/cars/car_132_8.jpg"
    ]
  },
  {
    "id": 133,
    "brand": "Volkswagen",
    "model": "Bora 1.5L 自动时尚版",
    "year": 2022,
    "price": 7800,
    "priceLabel": "$7,800",
    "mileage": "40000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_133_133.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_133_133.jpg",
      "uploads/cars/car_133_2.jpg",
      "uploads/cars/car_133_3.jpg",
      "uploads/cars/car_133_4.jpg",
      "uploads/cars/car_133_5.jpg",
      "uploads/cars/car_133_6.jpg",
      "uploads/cars/car_133_7.jpg",
      "uploads/cars/car_133_8.jpg"
    ]
  },
  {
    "id": 134,
    "brand": "Volkswagen",
    "model": "Santana 1.5L 自动风尚版",
    "year": 2021,
    "price": 5800,
    "priceLabel": "$5,800",
    "mileage": "50000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_134_134.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_134_134.jpg",
      "uploads/cars/car_134_2.jpg",
      "uploads/cars/car_134_3.jpg",
      "uploads/cars/car_134_4.jpg",
      "uploads/cars/car_134_5.jpg",
      "uploads/cars/car_134_6.jpg",
      "uploads/cars/car_134_7.jpg",
      "uploads/cars/car_134_8.jpg"
    ]
  },
  {
    "id": 135,
    "brand": "Volkswagen",
    "model": "Golf 280TSI DSG Pro",
    "year": 2023,
    "price": 14200,
    "priceLabel": "$14,200",
    "mileage": "22000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_135_135.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_135_135.jpg",
      "uploads/cars/car_135_2.jpg",
      "uploads/cars/car_135_3.jpg",
      "uploads/cars/car_135_4.jpg",
      "uploads/cars/car_135_5.jpg",
      "uploads/cars/car_135_6.jpg",
      "uploads/cars/car_135_7.jpg",
      "uploads/cars/car_135_8.jpg"
    ]
  },
  {
    "id": 136,
    "brand": "Volkswagen",
    "model": "Touran 280TSI 7座舒适版",
    "year": 2022,
    "price": 11200,
    "priceLabel": "$11,200",
    "mileage": "35000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_136_136.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_136_136.jpg",
      "uploads/cars/car_136_2.jpg",
      "uploads/cars/car_136_3.jpg",
      "uploads/cars/car_136_4.jpg",
      "uploads/cars/car_136_5.jpg",
      "uploads/cars/car_136_6.jpg",
      "uploads/cars/car_136_7.jpg",
      "uploads/cars/car_136_8.jpg"
    ]
  },
  {
    "id": 137,
    "brand": "Volkswagen",
    "model": "Teramont 380TSI 四驱豪华版",
    "year": 2021,
    "price": 24800,
    "priceLabel": "$24,800",
    "mileage": "46000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_137_137.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_137_137.jpg",
      "uploads/cars/car_137_2.jpg",
      "uploads/cars/car_137_3.jpg",
      "uploads/cars/car_137_4.jpg",
      "uploads/cars/car_137_5.jpg",
      "uploads/cars/car_137_6.jpg",
      "uploads/cars/car_137_7.jpg",
      "uploads/cars/car_137_8.jpg"
    ]
  },
  {
    "id": 138,
    "brand": "Volkswagen",
    "model": "CC 380TSI 夺目版",
    "year": 2022,
    "price": 18800,
    "priceLabel": "$18,800",
    "mileage": "32000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_138_138.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_138_138.jpg",
      "uploads/cars/car_138_2.jpg",
      "uploads/cars/car_138_3.jpg",
      "uploads/cars/car_138_4.jpg",
      "uploads/cars/car_138_5.jpg",
      "uploads/cars/car_138_6.jpg",
      "uploads/cars/car_138_7.jpg",
      "uploads/cars/car_138_8.jpg"
    ]
  },
  {
    "id": 139,
    "brand": "Volkswagen",
    "model": "ID.4 Crozz 纯电动 SUV",
    "year": 2023,
    "price": 19800,
    "priceLabel": "$19,800",
    "mileage": "15000 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_139_139.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_139_139.jpg",
      "uploads/cars/car_139_2.jpg",
      "uploads/cars/car_139_3.jpg",
      "uploads/cars/car_139_4.jpg",
      "uploads/cars/car_139_5.jpg",
      "uploads/cars/car_139_6.jpg",
      "uploads/cars/car_139_7.jpg",
      "uploads/cars/car_139_8.jpg"
    ]
  },
  {
    "id": 140,
    "brand": "Chery",
    "model": "瑞虎7  1.5T CVT尊贵版",
    "year": 2024,
    "price": 8722,
    "priceLabel": "$8,722",
    "mileage": "20000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_140_140.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_140_140.jpg",
      "uploads/cars/car_140_2.jpg",
      "uploads/cars/car_140_3.jpg",
      "uploads/cars/car_140_4.jpg",
      "uploads/cars/car_140_5.jpg",
      "uploads/cars/car_140_6.jpg",
      "uploads/cars/car_140_7.jpg",
      "uploads/cars/car_140_8.jpg"
    ]
  },
  {
    "id": 141,
    "brand": "Chery",
    "model": "瑞虎3x  1.5L CVT时尚版",
    "year": 2023,
    "price": 7194,
    "priceLabel": "$7,194",
    "mileage": "19000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_141_141.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_141_141.jpg",
      "uploads/cars/car_141_2.jpg",
      "uploads/cars/car_141_3.jpg",
      "uploads/cars/car_141_4.jpg",
      "uploads/cars/car_141_5.jpg",
      "uploads/cars/car_141_6.jpg",
      "uploads/cars/car_141_7.jpg",
      "uploads/cars/car_141_8.jpg"
    ]
  },
  {
    "id": 142,
    "brand": "Chery",
    "model": "艾瑞泽5  1.5L CVT领锐版",
    "year": 2016,
    "price": 1972,
    "priceLabel": "$1,972",
    "mileage": "100000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_142_142.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_142_142.jpg",
      "uploads/cars/car_142_2.jpg",
      "uploads/cars/car_142_3.jpg",
      "uploads/cars/car_142_4.jpg",
      "uploads/cars/car_142_5.jpg",
      "uploads/cars/car_142_6.jpg",
      "uploads/cars/car_142_7.jpg",
      "uploads/cars/car_142_8.jpg"
    ]
  },
  {
    "id": 143,
    "brand": "BYD",
    "model": "元新能源  EV360 智联创酷型",
    "year": 2018,
    "price": 4861,
    "priceLabel": "$4,861",
    "mileage": "50000 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_143_143.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_143_143.jpg",
      "uploads/cars/car_143_2.jpg",
      "uploads/cars/car_143_3.jpg",
      "uploads/cars/car_143_4.jpg",
      "uploads/cars/car_143_5.jpg",
      "uploads/cars/car_143_6.jpg",
      "uploads/cars/car_143_7.jpg",
      "uploads/cars/car_143_8.jpg"
    ]
  },
  {
    "id": 144,
    "brand": "BYD",
    "model": "宋PLUS新能源  DM-i 112KM 尊荣型",
    "year": 2025,
    "price": 13875,
    "priceLabel": "$13,875",
    "mileage": "11000 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_144_144.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_144_144.jpg",
      "uploads/cars/car_144_2.jpg",
      "uploads/cars/car_144_3.jpg",
      "uploads/cars/car_144_4.jpg",
      "uploads/cars/car_144_5.jpg",
      "uploads/cars/car_144_6.jpg",
      "uploads/cars/car_144_7.jpg",
      "uploads/cars/car_144_8.jpg"
    ]
  },
  {
    "id": 145,
    "brand": "BYD",
    "model": "秦L  DM-i 智驾版 120KM超越型",
    "year": 2025,
    "price": 11917,
    "priceLabel": "$11,917",
    "mileage": "7000 km",
    "fuel_type": "PHEV",
    "transmission": "自动",
    "image": "uploads/cars/car_145_145.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_145_145.jpg",
      "uploads/cars/car_145_2.jpg",
      "uploads/cars/car_145_3.jpg",
      "uploads/cars/car_145_4.jpg",
      "uploads/cars/car_145_5.jpg",
      "uploads/cars/car_145_6.jpg",
      "uploads/cars/car_145_7.jpg",
      "uploads/cars/car_145_8.jpg"
    ]
  },
  {
    "id": 146,
    "brand": "BYD",
    "model": "海狮07 EV  610智航版",
    "year": 2024,
    "price": 16639,
    "priceLabel": "$16,639",
    "mileage": "52000 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_146_146.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_146_146.jpg",
      "uploads/cars/car_146_2.jpg",
      "uploads/cars/car_146_3.jpg",
      "uploads/cars/car_146_4.jpg",
      "uploads/cars/car_146_5.jpg",
      "uploads/cars/car_146_6.jpg",
      "uploads/cars/car_146_7.jpg",
      "uploads/cars/car_146_8.jpg"
    ]
  },
  {
    "id": 147,
    "brand": "Haval",
    "model": "哈弗F7  1.5T 两驱i潮",
    "year": 2020,
    "price": 7472,
    "priceLabel": "$7,472",
    "mileage": "32000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_147_147.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_147_147.jpg",
      "uploads/cars/car_147_2.jpg",
      "uploads/cars/car_147_3.jpg",
      "uploads/cars/car_147_4.jpg",
      "uploads/cars/car_147_5.jpg",
      "uploads/cars/car_147_6.jpg",
      "uploads/cars/car_147_7.jpg",
      "uploads/cars/car_147_8.jpg"
    ]
  },
  {
    "id": 148,
    "brand": "Haval",
    "model": "哈弗M6  PLUS 1.5T 手动豪华智联型",
    "year": 2023,
    "price": 7750,
    "priceLabel": "$7,750",
    "mileage": "11000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_148_148.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_148_148.jpg",
      "uploads/cars/car_148_2.jpg",
      "uploads/cars/car_148_3.jpg",
      "uploads/cars/car_148_4.jpg",
      "uploads/cars/car_148_5.jpg",
      "uploads/cars/car_148_6.jpg",
      "uploads/cars/car_148_7.jpg",
      "uploads/cars/car_148_8.jpg"
    ]
  },
  {
    "id": 149,
    "brand": "MG",
    "model": "名爵ZS  180DVVT 自动全球百万918版",
    "year": 2022,
    "price": 6778,
    "priceLabel": "$6,778",
    "mileage": "88000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_149_149.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_149_149.jpg",
      "uploads/cars/car_149_2.jpg",
      "uploads/cars/car_149_3.jpg",
      "uploads/cars/car_149_4.jpg",
      "uploads/cars/car_149_5.jpg",
      "uploads/cars/car_149_6.jpg",
      "uploads/cars/car_149_7.jpg",
      "uploads/cars/car_149_8.jpg"
    ]
  },
  {
    "id": 150,
    "brand": "Geely",
    "model": "缤越 2025款 1.5L CVT 超能 MAX",
    "year": 2025,
    "price": 10500,
    "priceLabel": "$10,500",
    "mileage": "15000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_150_150.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_150_150.jpg",
      "uploads/cars/car_150_2.jpg",
      "uploads/cars/car_150_3.jpg",
      "uploads/cars/car_150_4.jpg",
      "uploads/cars/car_150_5.jpg",
      "uploads/cars/car_150_6.jpg",
      "uploads/cars/car_150_7.jpg",
      "uploads/cars/car_150_8.jpg"
    ]
  },
  {
    "id": 151,
    "brand": "Geely",
    "model": "星越L 2025款 东方曜 2.0TD 自动揽星版",
    "year": 2025,
    "price": 17300,
    "priceLabel": "$17,300",
    "mileage": "18000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_151_151.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_151_151.jpg",
      "uploads/cars/car_151_2.jpg",
      "uploads/cars/car_151_3.jpg",
      "uploads/cars/car_151_4.jpg",
      "uploads/cars/car_151_5.jpg",
      "uploads/cars/car_151_6.jpg",
      "uploads/cars/car_151_7.jpg",
      "uploads/cars/car_151_8.jpg"
    ]
  },
  {
    "id": 152,
    "brand": "Geely",
    "model": "帝豪 2026款 第5代 1.5L CVT尊贵型",
    "year": 2026,
    "price": 9500,
    "priceLabel": "$9,500",
    "mileage": "5000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_152_152.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_152_152.jpg",
      "uploads/cars/car_152_2.jpg",
      "uploads/cars/car_152_3.jpg",
      "uploads/cars/car_152_4.jpg",
      "uploads/cars/car_152_5.jpg",
      "uploads/cars/car_152_6.jpg",
      "uploads/cars/car_152_7.jpg",
      "uploads/cars/car_152_8.jpg"
    ]
  },
  {
    "id": 153,
    "brand": "Changan",
    "model": "长安CS75PLUS 2025款 第四代 1.5T 新蓝鲸 智慧鲸悦版",
    "year": 2025,
    "price": 13200,
    "priceLabel": "$13,200",
    "mileage": "12000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_153_153.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_153_153.jpg",
      "uploads/cars/car_153_2.jpg",
      "uploads/cars/car_153_3.jpg",
      "uploads/cars/car_153_4.jpg",
      "uploads/cars/car_153_5.jpg",
      "uploads/cars/car_153_6.jpg",
      "uploads/cars/car_153_7.jpg",
      "uploads/cars/car_153_8.jpg"
    ]
  },
  {
    "id": 154,
    "brand": "Changan",
    "model": "逸动 2026款 第四代 1.5T 500Bar 智享型",
    "year": 2026,
    "price": 10500,
    "priceLabel": "$10,500",
    "mileage": "8000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_154_154.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_154_154.jpg",
      "uploads/cars/car_154_2.jpg",
      "uploads/cars/car_154_3.jpg",
      "uploads/cars/car_154_4.jpg",
      "uploads/cars/car_154_5.jpg",
      "uploads/cars/car_154_6.jpg",
      "uploads/cars/car_154_7.jpg",
      "uploads/cars/car_154_8.jpg"
    ]
  },
  {
    "id": 155,
    "brand": "Changan",
    "model": "长安CS55PLUS 2022款 第二代 1.5T DCT尊贵型",
    "year": 2022,
    "price": 10800,
    "priceLabel": "$10,800",
    "mileage": "25000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_155_155.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_155_155.jpg",
      "uploads/cars/car_155_2.jpg",
      "uploads/cars/car_155_3.jpg",
      "uploads/cars/car_155_4.jpg",
      "uploads/cars/car_155_5.jpg",
      "uploads/cars/car_155_6.jpg",
      "uploads/cars/car_155_7.jpg",
      "uploads/cars/car_155_8.jpg"
    ]
  },
  {
    "id": 156,
    "brand": "Li Auto",
    "model": "理想L7 2025款 Ultra 智能焕新版",
    "year": 2025,
    "price": 35500,
    "priceLabel": "$35,500",
    "mileage": "15000 km",
    "fuel_type": "PHEV",
    "transmission": "自动",
    "image": "uploads/cars/car_156_156.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_156_156.jpg",
      "uploads/cars/car_156_2.jpg",
      "uploads/cars/car_156_3.jpg",
      "uploads/cars/car_156_4.jpg",
      "uploads/cars/car_156_5.jpg",
      "uploads/cars/car_156_6.jpg",
      "uploads/cars/car_156_7.jpg",
      "uploads/cars/car_156_8.jpg"
    ]
  },
  {
    "id": 157,
    "brand": "AITO",
    "model": "问界M7 2026款 增程 Ultra四驱版 5座192线激光雷达）",
    "year": 2026,
    "price": 38800,
    "priceLabel": "$38,800",
    "mileage": "12000 km",
    "fuel_type": "PHEV",
    "transmission": "自动",
    "image": "uploads/cars/car_157_157.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_157_157.jpg",
      "uploads/cars/car_157_2.jpg",
      "uploads/cars/car_157_3.jpg",
      "uploads/cars/car_157_4.jpg",
      "uploads/cars/car_157_5.jpg",
      "uploads/cars/car_157_6.jpg",
      "uploads/cars/car_157_7.jpg",
      "uploads/cars/car_157_8.jpg"
    ]
  },
  {
    "id": 158,
    "brand": "Luxeed",
    "model": "智界S7 2024款 Pro",
    "year": 2024,
    "price": 28500,
    "priceLabel": "$28,500",
    "mileage": "18000 km",
    "fuel_type": "EV",
    "transmission": "自动",
    "image": "uploads/cars/car_158_158.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_158_158.jpg",
      "uploads/cars/car_158_2.jpg",
      "uploads/cars/car_158_3.jpg",
      "uploads/cars/car_158_4.jpg",
      "uploads/cars/car_158_5.jpg",
      "uploads/cars/car_158_6.jpg",
      "uploads/cars/car_158_7.jpg",
      "uploads/cars/car_158_8.jpg"
    ]
  },
  {
    "id": 159,
    "brand": "GAC",
    "model": "传祺GS3 2026款 影速 270T 劲享版",
    "year": 2026,
    "price": 11500,
    "priceLabel": "$11,500",
    "mileage": "8000 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_159_159.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_159_159.jpg",
      "uploads/cars/car_159_2.jpg",
      "uploads/cars/car_159_3.jpg",
      "uploads/cars/car_159_4.jpg",
      "uploads/cars/car_159_5.jpg",
      "uploads/cars/car_159_6.jpg",
      "uploads/cars/car_159_7.jpg",
      "uploads/cars/car_159_8.jpg"
    ]
  },
  {
    "id": 160,
    "brand": "BYD",
    "model": "海狮05 EV 520KM旗舰智航版",
    "year": 2025,
    "price": 15000,
    "priceLabel": "$15,000",
    "mileage": "5200 km",
    "fuel_type": "Petrol",
    "transmission": "手动",
    "image": "uploads/cars/car_160_160.jpg",
    "is_featured": 1,
    "is_new_arrival": 1,
    "images": [
      "uploads/cars/car_160_160.jpg",
      "uploads/cars/car_160_2.jpg",
      "uploads/cars/car_160_3.jpg",
      "uploads/cars/car_160_4.jpg",
      "uploads/cars/car_160_5.jpg",
      "uploads/cars/car_160_6.jpg",
      "uploads/cars/car_160_7.jpg",
      "uploads/cars/car_160_8.jpg"
    ]
  }
];
